# Generated by Django 4.2.11 on 2024-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_cart_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ref',
            field=models.CharField(max_length=100),
        ),
    ]
