# Generated by Django 5.0.6 on 2024-07-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
    ]
