# Generated by Django 4.2.11 on 2024-06-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_cart_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checker',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
